#!/usr/bin/env bun

/**
 * Generate TypeScript types from Supabase database schema
 * 
 * Usage:
 *   bun run scripts/generate-types.ts
 * 
 * Requires:
 *   - SUPABASE_PROJECT_ID environment variable
 *   - npx (comes with npm/node - no installation needed!)
 *   - Optional: Authenticated with Supabase (npx supabase login)
 */

import { execSync } from 'child_process'
import { writeFileSync } from 'fs'
import { join } from 'path'

const PROJECT_ID = process.env.SUPABASE_PROJECT_ID
const OUTPUT_PATH = join(process.cwd(), 'types', 'database.ts')

if (!PROJECT_ID) {
  console.error('❌ SUPABASE_PROJECT_ID environment variable is required')
  console.error('   Set it in your .env.local file or export it:')
  console.error('   export SUPABASE_PROJECT_ID=your-project-id')
  process.exit(1)
}

console.log('🔄 Generating TypeScript types from Supabase schema...')
console.log(`   Project ID: ${PROJECT_ID}`)
console.log(`   Output: ${OUTPUT_PATH}`)

try {
  // Generate types using Supabase CLI
  // Use npx to avoid requiring global installation
  const command = `npx supabase gen types typescript --project-id ${PROJECT_ID}`
  
  console.log(`\n📝 Running: ${command}`)
  console.log('   (Using npx - no global installation needed)\n')
  const types = execSync(command, {
    encoding: 'utf-8',
    stdio: 'pipe',
  })

  // Add header comment
  const header = `/**
 * This file is auto-generated from your Supabase database schema.
 * 
 * DO NOT EDIT THIS FILE MANUALLY.
 * 
 * To regenerate:
 *   1. Set SUPABASE_PROJECT_ID in your environment
 *   2. Run: bun run scripts/generate-types.ts
 * 
 * Or using Supabase CLI directly:
 *   supabase gen types typescript --project-id YOUR_PROJECT_ID > types/database.ts
 * 
 * Last generated: ${new Date().toISOString()}
 */

`

  // Write to file
  writeFileSync(OUTPUT_PATH, header + types, 'utf-8')

  console.log('✅ Types generated successfully!')
  console.log(`   File: ${OUTPUT_PATH}`)
  console.log('\n💡 Next steps:')
  console.log('   1. Review the generated types')
  console.log('   2. Commit to version control')
  console.log('   3. Regenerate after schema changes')
} catch (error: any) {
  console.error('❌ Error generating types:', error.message)
  console.error('\n🔧 Troubleshooting:')
  console.error('   1. Verify PROJECT_ID is correct (get from Supabase Dashboard → Settings → API)')
  console.error('   2. Ensure npx is available (comes with npm/node)')
  console.error('   3. Try running manually: npx supabase gen types typescript --project-id YOUR_PROJECT_ID')
  console.error('   4. If using installed CLI, ensure you are logged in: supabase login')
  console.error('\n💡 Installation methods:')
  console.error('   - npx (recommended): No installation needed!')
  console.error('   - Scoop: scoop install supabase')
  console.error('   - winget: winget install Supabase.CLI')
  console.error('   - Direct download: https://github.com/supabase/cli/releases')
  process.exit(1)
}

